[package]
name = "ptu"
version = "0.1.0"
edition = "2024"

[dependencies]
alpm = "5.0.1"
color-eyre = "0.6.5"
ratatui = "0.30.0"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
textwrap = "0.16.2"
tokio = { version = "1", features = ["rt-multi-thread", "sync"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
toml = "0.8"
tracing-appender = "0.2"
